version: '3.8'

services:
  localai:
    image: quay.io/go-skynet/local-ai:latest
    ports:
      - "8080:8080"
    volumes:
      - ./models:/models
      - ./config:/build
    environment:
      - MODELS_PATH=/models
