version: '3.8'

services:
  emotion-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./dictionaries:/app/dictionaries
    command: streamlit run app.py --server.address=0.0.0.0 --server.port=8501
